---
 - name: Checking Memory
   fail:
        msg: You have not supported the memory requirements
   when: ansible_memtotal_mb <= 1500 
          






                                                                                                          
                                                                                                          
