---
      - name: Check the memory status
        shell: ansible all -m setup -a 'filter=ansible_memtotal_mb' | grep ansible_memtotal_mb | awk -F ":" '{print $2}'
        register: output

      - set_fact: memory_a=[1500]

#      - debug:
#            var: output

 

      - debug: 
            msg: less memory
        when: output.stdout|int >= memory_a
   
      - debug:
            msg: "You have supported the memory requirements"
