---  
 - debug:    
     msg: "Swap is disabled , playbooks shall proceed"  
   when: ansible_swaptotal_mb == 0 

 - fail:        
      msg: "Swap is enabled , kindly disable swap"    
   when: ansible_swaptotal_mb != 0                                                                        
