---
 - name: Check Swap  
   fail:        
      msg: "Swap is enabled , kindly disable swap"    
   when: ansible_swaptotal_mb != 0                                                                        
