---
 - name: Transfer the kube config file to url
   shell: curl -i -X POST \
               -H "Content-Type= multipart/form-data" \
               -F "kube_config=@/root/.kube/config" \
                   http://172.16.17.18:1920/v1/kube_config
